### ISSUE TITLE
IBM.com style model work - adopter interview (Donna Walker)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#101]
#### [Donna Walker](https://w3.ibm.com/bluepages/profile.html?uid=4A7434897)
![Screen Shot 2020-07-06 at 6 17 38 PM](https://user-images.githubusercontent.com/45213839/86794355-08fe4200-c032-11ea-9dc5-e475d7258323.png)

(Finance and Operations Team)
Director - IBM Technical Content, Training and Skills
Finance and Operations

---

#### Note

(Coming soon - Wonil)

#### Interview questions

- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What are your fears?
- [ ] What are your pain points?
- [ ] Who are your users/adopters?
- [ ] What is your definition of success?
- [ ] What are your business needs?
- [ ] How do you see this be operational for your team?
- [ ] How is the IBM.com Style Model fits into the Journey or vice versa?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by Jennifer-Price** [comment]
@JennySanchez Patrick will be the one the Patterns Team will speak to for F&O. We can close Donna's item here.

**Comment by JennySanchez** [comment]
@JennySanchez Got it. Thank you!
