### ISSUE TITLE
🙅‍♂️  Placeholder/IBM.com style model work - adopter interview (Doug Powell )

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#103]
#### [Doug Powell](https://w3.ibm.com/bluepages/profile.html?uid=3G2882897)
![Screen Shot 2020-07-06 at 6 22 19 PM](https://user-images.githubusercontent.com/45213839/86794450-28956a80-c032-11ea-92e9-924b9257f9bd.png)

(Watson Health)
VP, Designer Practices & Community  Distinguished Designer
IBM Cloud and Cognitive Software 

---

#### Note

(Coming soon - Wonil)

#### Interview questions

- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What are your fears?
- [ ] What are your pain points?
- [ ] Who are your users/adopters?
- [ ] What is your definition of success?
- [ ] What are your business needs?
- [ ] How do you see this be operational for your team?
- [ ] How is the IBM.com Style Model fits into the Journey or vice versa?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Holdover from pre-Patterns work — no longer relevant to current work
