### ISSUE TITLE
Dark theme masthead for Knowledge Center

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#106]
A request is coming from the Knowledge Center team regarding the masthead.

1. Knowledge Center is asking for a dark themed L0 masthead because most of the traffic is from product experiences. 
2. They also want to provide product teams with different color theme options to match their products.

**Comment by wonilsuhibm** [comment]
##### My questions and perspectives on the dark theme:
- There are products using light themes as well. How will the dark masthead work with this?
- There are many products on IBM.com as well, which are white themed.
- Many products that use dark theme also apply the dark theme to the entire page. Does this mean that the entire Knowledge Center has to be dark themed?

##### My perspectives on allowing teams to choose their own theme
- This could work as long as the documents themselves are designed as stand-alone experience detached from Knowledge Center

##### Final thoughts and ideas
- If we are going to allow different color themes for different product documentations, the global masthead for Knowledge Center should be white in order to maintain consistency with the rest of IBM.com. Knowledge center did mention this as an option: white masthead for the landing page, and multiple themes for the documentations themselves. We will need to see the designs to understand how this will work.

**Comment by photodow** [comment]
Personally, I feel like for a component or pattern to be apart of the IBM.com library it should have a couple of common features. One of them being the theme-ability of it. By deciding this one gets these themes, this one gets only white, and that one gets g90 we're overcomplicating our system, making it harder to provide support, harder for our adopters to understand. vs. saying everything is theme-able, here are 4 themes, here's how to use it. If something isn't working in one of the themes then it's clearly broken.

> They also want to provide product teams with different color theme options to match their products.

What does this mean?

> - There are products using light themes as well. How will the dark masthead work with this?
> - There are many products on IBM.com as well, which are white themed.
> - Many products that use dark theme also apply the dark theme to the entire page. Does this mean that the entire Knowledge Center has to be dark themed?

@wonilsuhibm Can we say that a specific page is a white theme? Don't we have zoned theming that breaks this idea? It's rare we have a template made up entirely of one theme.


What does the knowledge center journey look like? Do we have any user research to back up an concerns that switching from a white masthead to a g90 masthead is a problem?
