### ISSUE TITLE
Image production standards

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#108]
Provide image production standards for the new DAM.

**Comment by wonilsuhibm** [comment]
The existing renditions in Bynder (current DAM) are:

- Original
- LowRes Original
- Retina Display 2800 x 1867 px
- Leadspace 1400 x 933 px
- Content 600 x 340 px
- Inline 480 x 360 px
- Thumbnail 150 x 111px

**Comment by wonilsuhibm** [comment]
# Meeting minutes

### Current DAM example
https://dam.ibm.com/media/?mediaId=ACD6C702-434E-41A1-96BC3ADAA66B2FF6

### Send rendition size mappings to Molly Reinganum
2800 -> 3608
1400 -> 1584
600 -> 640
480 -> 480
150 -> 320

### Timeline
Initial by October

**Comment by wonilsuhibm** [comment]
### Proposal
| Current | New | 
|:---|:---|
| Retina Display 2800 x 1867 | - - - | 
| Lead space 1400 x 933 (3:2) | Lead space 1584 x 560 (standard max w x h) | 
| (new) | Lead space retina 3168 x 1120 |
| (new) | Large 1312 x 874 (3:2) | 
| (new) | Large retina 2624 x 1748 (3:2) |
| Content 600 x 340 | Medium 674 x 672 x 448 (3:2) |
| (new) | Medium retina 1348 x 896 (3:2) |
| Inline 480 x 360 (4:3) | Small 480 x 320 (3:2) |
| (new) | Small retina 960 x 640 (3:2) |
| Thumbnail 150 x 111px | Tile 160 x 160 (1:1) |
| (new) | Tile retina 320x320 (1:1) |

Additional notes:
- The labels are somewhat arbitrary if I understand correctly.
- New renditions are based on the new breakpoints.
- New renditions are being proposed to handle retina displays
- The aspects ratio of 3:2 is being used as the standard when makes sense since it sits in the middle of all the other standard breakpoints, which increases predictability and reusability of the original image. (see the diagram below)
<img width="708" alt="Screen Shot 2020-07-22 at 12 13 12 PM" src="https://user-images.githubusercontent.com/30183447/88200871-bcf7f380-cc14-11ea-98b9-70432b1cc17e.png">

**Comment by wonilsuhibm** [comment]
### Proposal 2 (aspect ratio based)

##### Large breakpoint and up
| Name | Aspect ratio | size | 
|:---|:---|:---|
| Large lead space | (standard max w x h) | 1584 x 560 | 
| Large lead space| (standard max w x h) | retina 3168 x 1120 |
| Large 4x3 | 4:3 | 1312 x 984 |
| Large 4x3 Retina | 4:3 | 2624 x 1968 |
|Large 3:2 | 3:2 | 1312 x 874 |
|Large 3:2 retina | 3:2 | 2624 x 1748 |
|Large 16x9 | 16:9 | 1312 x 738 |
|Large 16x9 retina | 16:9 retina | 2624 x 1476 |

##### Medium breakpoint and up
| Name | Aspect ratio | size | 
|:---|:---|:---|
| Medium lead space | (standard max w x h) | 672 x 400 | 
| Medium lead space | (standard max w x h) | retina 1344 x 800 |
| Medium 4x3 | 4:3 | 672 x 504 |
| Medium 4x3 Retina | 4:3 | 1344 x 1008 |
| Medium 3:2 | 3:2 | 672 x 448 |
| Medium 3:2 retina | 3:2 | 1344 x 896 |
| Medium 16x9 | 16:9 | 672 x 378 |
| Medium 16x9 retina | 16:9 retina | 1344 x 756 |

**Comment by photodow** [comment]
@wonilsuhibm should testing performance play a part in this standard?
