### ISSUE TITLE
Video player re-skin

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#113]
The current Kaltura video player uses their default theme (text, color, icon, etc). We want to update this to IDL specs. 

### Additional information
- The Brand team passed this new [design file](https://ibm.box.com/s/ndj6pettuuw2346rnwk9svjapzhfs5ve).

**Comment by RobertaJHahn** [comment]
Can be closed.  This work should be done by the MediaCenter team.
