### ISSUE TITLE
Account page redesign

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#115]
DDS owns this page: https://www.ibm.com/account/us-en/

Details to come via convo with leadership.

**Comment by JennySanchez** [comment]
@wonilsuhibm Any update from the DDS Leadership Team? Can you help by providing a bit more information about the task?

**Comment by shixiedesign** [comment]
Duplicate of https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5978
