### ISSUE TITLE
iOS video player behavior

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#116]
Currently, when the user taps the play button on the video player in an iOS device, the video starts playing but muted. This is per the iOS's restrictions. We have two options:

- Option 1: keep it as is. Expect the user to raise the volume.
- Option 2: change it to non-auto-play. In this scenario, the user will be presented with a second play button, which is the iOS native play button, and has to tap it again in order to play the video. This time, the video will play with sound.

This story is to test the two options and get users' feedback in order to choose the better option.

**Comment by RobertaJHahn** [comment]
Decided to leave as is.  Closing
