### ISSUE TITLE
Layout foundations - Target: Feb 21

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#117]
Start with [4-12] and [16] as the two overarching layout options, and create guidelines around them.

**Comment by ghost** [comment]
Created a [Box note](https://ibm.box.com/s/1lm1zs6zcof4epd5k9i7wbk00o82glsj) and a [Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1603810864832?sender=wonilsuh19286&key=b29a87e7-78a0-43fe-ad27-ade9c2dd5aac) for content ideation.

Currently, collecting content ideas on the Mural board.

@JennySanchez

**Comment by RobertaJHahn** [comment]
@shixiedesign I am trying to clean up old issues so that we don't keep carrying work from one sprint to the next.  Can you decide whether this issue is still needed.  If not, just comment and move to Done.  Thanks.

**Comment by shixiedesign** [comment]
I've found a lot of materials Wonil's drafted. 

This story can be closed and the work will be tracked in Website audit & planning issue https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/860
