### ISSUE TITLE
Carousel MVP: research

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#125]
### User story 1  - End user
*TBD*

### User story 2  - DDS Designer
As a DDS designer, I need to understand:
- the needs for different carousel features
- existing design examples and their associated useability data
- existing research findings (both internal and external)

so that I can start design explorations.

### Notes
This research is to understand the general Carousel feature, the pros, cons, when to use, and when to not use. Once we have this understanding, we may end up creating multiple and more focused research and/or design epics for each application list below.

#### Potential applications
- There are a few Cloud layout components that use Carousel feature.
- We have the wedding cake vision for the Lightbox media viewer component that uses the carousel feature.
- The home page uses carousel.

### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [Box folder](https://ibm.box.com/s/stkuousskcrw0t42hlqfogdd1k240btx)
- [LUX research](https://lux.w3ibm.mybluemix.net/)

### Acceptance Criteria
- [ ] Research findings are available in the above Box folder
- [ ] The next story has been updated with the research findings

**Comment by jacobottesen-dgc** [comment]
Research for carousel can be found here in box: 
https://ibm.box.com/s/v27104nxjyfwrwjij3nvtur67ji59m4w
