### ISSUE TITLE
Carousel MVP: design study

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#131]
### User story 1  - End user
*TBD*

### User story 2  - DDS Designer
As a DDS designer, I need to understand:
- the needs for different carousel features
- existing design examples and their associated useability data
- existing research findings (both internal and external)

so that I can start design explorations.

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by jacobottesen-dgc** [comment]
In the process of exploring multiple progress indicators for carousel with UI designs in Sketch and multiple prototypes in Adobe XD.

![Screen Shot 2020-10-01 at 8.37.05 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/fe3dc8b0-440f-49cc-924a-5c1b263c6bc7)

![Screen Shot 2020-10-01 at 8.35.22 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/e41169c1-6bf9-4f84-ae4a-b4274c5459bb)
