### ISSUE TITLE
Carousel MVP:  Final design

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#132]
### User story 1  - End user
*TBD*

### User story 2  - DDS Designer
As a DDS designer, I need to understand:
- the needs for different carousel features
- existing design examples and their associated useability data
- existing research findings (both internal and external)

so that I can start design explorations.

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Final designs are available
- [ ] Design spec issue has been created on the Agile board with the documentation needed and the work scheduled.

**Comment by jacobottesen-dgc** [comment]
During the carousel sync up meeting with Olivia, James and I we came up with these next steps:

- Update carousel control icons from chevron to caret 
- Update user test to be A/B testing showing to options. A. Slider bar with caret icon controls with numbers in the middle. B. Add the pagination component from Carbon expressive as controls 
- Meet with accessibility to discuss tabbing options 
- Try building prototype with tabbing in XD

cc. @wonilsuhibm

**Comment by jacobottesen-dgc** [comment]
Design specs for (MVP) Carousel component can be viewed below: 

PDF file:
https://ibm.box.com/s/1aj7r0y9j73lvauv6dqtt73d2b6kma6v

Sketch file:
https://ibm.box.com/s/dr4mko4st4q0fv0ezm6my2jqkblfzdkn
