### ISSUE TITLE
Ideation and planning for the Contribution section content updates and publishing

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#141]
#### Objective

We need to provide adopter guidance on how to contribute back to the IBM.com Library so we can grow and scale the IBM.com Library.

#### Identified areas

- Design specs
- Functional specs
- Guideline crafting
- Develop
- Design

#### Note

- View what we currently have for the development contribution guideline [here](https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/.github/CONTRIBUTING.md#contribution-guidelines).

- Below are what Carbon currently has on the [Carbon website](https://www.carbondesignsystem.com/contributing/overview/).
![Screen Shot 2020-09-04 at 12.27.06 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/9b4795cd-38cc-41bc-8c5e-2b63f36f74a5)

**Comment by JennySanchez** [comment]
**Note:**
Set up this [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1601477057937?sender=chsanche&key=ce766f2c-11c4-4e87-a34d-cc9ae72548a6) for discussion session schedule 2:00 pm ET on 09/30.

**Comment by JennySanchez** [comment]
- Link to WIP Contribution Model Approach.pptx: https://ibm.box.com/s/rc5xrrhbmf2q2eqm2qu0kgf0ggaww4s1
- Link to WIP Mural: https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1600172216140/f201aa0d94c4412af9663e0acf18063588dfb5a8

**Comment by JennySanchez** [comment]
@jeffchew @ljcarot @wonilsuhibm 

Can you take a look at the initial proposal for the "Contributing" section content planning for the website and let me know what do you think? I need feedback for the page naming (yellow) and the content/section (light yellow) for each page?

![Screen Shot 2020-10-05 at 2 14 51 PM](https://user-images.githubusercontent.com/45213839/95121816-359b2600-0715-11eb-949a-d8bcb38e5ee8.png)

For the "First steps to contributing" section. The idea is to have some basic info around opening a PR. Below is an example for Components and it's the same format as [Carbon](https://www.carbondesignsystem.com/contributing/component).

![Screen Shot 2020-10-05 at 2 21 49 PM](https://user-images.githubusercontent.com/45213839/95122521-426c4980-0716-11eb-8f84-4d6f0a395dfb.png)

---

**Note:** The **Contribution section** content update and crafting ideation can be viewed in the [Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1601477057937?sender=chsanche&key=ce766f2c-11c4-4e87-a34d-cc9ae72548a6).

**Next step:** Finalize the list. Once the list is finalized and agreed, I will create task issues on the Gitboard for prioritization so we can get the content updates and crafting started.

**Comment by ljcarot** [comment]
@JennySanchez I think we should start out with a simple list.  'Overview'; 'Components'; 'Patterns'.

**Comment by JennySanchez** [comment]
@ljcarot What do you think about the content/section (in light yellow) purposed to go into the 'Overview'; 'Components'; 'Patterns' pages?

We can create the MVP version content and refine or add content as we go.

**Comment by ljcarot** [comment]
@JennySanchez 'Overview' looks right. 'Components' looks like too many steps there.  'Patterns' should be only two steps too.  Can you DM me the Mural link?  It doesnt seem to want to open up for me.

**Comment by JennySanchez** [comment]
**Next step:**

We will craft content and design for the **Overview, Components, **and** Patterns** under the Contributions section.

**Comment by JennySanchez** [comment]
This task issue is no longer relevant to our work or priority and will be closed.
FYI: @RobertaJHahn
