### ISSUE TITLE
Scroll animation: Research

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#145]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
to be effectively immersed without being distracted

> so that I can:
physically engage with the page's narrative

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- Research sources:  ibm.com/cloud
- [box folder](https://ibm.box.com/s/ds85hj8qftok0tkwj82xopfbu4qvuk4i)

#### Acceptance Criteria
- [ ] Research findings are available in the above Box folder
- [ ] The next story has been updated with the research findings

**Comment by photodow** [comment]
Here is the box note with my study...
https://ibm.box.com/s/mauojg9vq6ordwbtxcb2g0ihbrj3hplq
