### ISSUE TITLE
New ideas for 2021 (disussion with Wonil needed)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#146]
## A few ideas to discuss with Wonl for the future IBM.com Library website development.

**Comment by JennySanchez** [comment]
### User Testing

**Potential tool: Usertesting.com**

For comparing feature set-ups along with options for the adopters to select the areas of what needs work. For example, content, visual reference, etc. The use case could be the ListView or Thumbnail View on the Components Overview Page.

For content feedback. Provide the adopters a set of information, after they read the content, answer a few questions to validate if the level of the content we presented is enough or needs editing to make sure it's the right level of information.

For IA structure. Ask an adopter to find a piece of information on the website. We can ask the adopter to talk out loud as they navigate through the website and using video recording to find insight or validate the structure. The use case could be the linking strategy between websites.

---

**Note:**

![Screen Shot 2020-09-10 at 3 00 40 PM](https://user-images.githubusercontent.com/45213839/92796185-946bba80-f376-11ea-9bf1-7217e8b99a56.png)
![Screen Shot 2020-09-10 at 3 00 44 PM](https://user-images.githubusercontent.com/45213839/92796190-95045100-f376-11ea-9353-8bf41088369c.png)

**Comment by JennySanchez** [comment]
### Style Model

A "info" icon to be next to each style model and show information around what is this template for and the intent (around the end-user need).

---
**Note:**
![Screen Shot 2020-09-10 at 3 06 25 PM](https://user-images.githubusercontent.com/45213839/92796921-38edfc80-f377-11ea-9974-0cb205d0d496.png)

**Comment by JennySanchez** [comment]
### Overall Visual Style
![Screenshot_2020-09-10 Material Design](https://user-images.githubusercontent.com/45213839/92797203-7a7ea780-f377-11ea-930c-654e60786e5a.jpg)

**Comment by RobertaJHahn** [comment]
Closing as dup of (#186)

**Comment by JennySanchez** [comment]
Hi, @RobertaJHahn This is not the duplicate issue of [186](https://github.com/carbon-design-system/digital-design-ideation/issues/186). This task issue contains NEW ideas I'd like to go over with Wonil and get feedback. Issue 186 (Ideation Cycle 1 - 2021 planning) is for the work we already know ahead of us.

I updated this issue title to be **New ideas for 2021** to avoid the confusion.

**Comment by JennySanchez** [comment]
I just saw you copied the content to the 186. Ok. Please discard the message above and I will close 146 and use 186 for discussion with Wonil.
