### ISSUE TITLE
Back to Top: design epic

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#153]
This epic contains an overview of the research and design performed to create this component. 

#### User Story 1 - End user
> As an [user role below]:
`ibm.com user`

> I would like to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Research findings are available and posted to the Box folder
- [ ] Design exploration is done and results posted to the Box folder
- [ ] Agile board epic is created to begin the functional specs work
- [ ] Final design is done and posted to the Box folder

**Comment by photodow** [comment]
Here are the designs and functional specs for here.

https://ibm.ent.box.com/folder/127553793291

**Comment by RobertaJHahn** [comment]
Closing as this epic was created in the Ideation repo for the Zenhub management.  The Zenhub board is obsolete.  The one Ideation issue has been linked to the original Carbon for ibm.com epic (#4462)
