### ISSUE TITLE
Scroll animation: Fade & Prototype

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#157]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by photodow** [comment]
Here is the prototype I built for this work.

https://codepen.io/photodow/full/vYKaaxK
