### ISSUE TITLE
Scroll animation: Final design

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#158]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Final designs are available
- [ ] Design spec issue has been created on the Agile board with the documentation needed and the work scheduled.

**Comment by photodow** [comment]
Only added design specs for the scroll into view utiliity.
https://ibm.box.com/s/raw94fq6dcfuey786zks0c6mx24kf0cd
