### ISSUE TITLE
Audio player: design study - Target sprint 21-02

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#163]
#### User Story 1 - End user
> As an [user role below]:
`ibm.com user`

> I would like to be able to:
`listen to audio files`

> so that I can:
`access the information I need on the ibm.com website`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- Offering manager is Gerard Ringuette.
- [Audio Player prototype created by MediaCenter team](https://pages.github.ibm.com/mediacenter/docs/examples/audio/)
- [box folder](https://ibm.ent.box.com/folder/124347059482?s=05ndo5nsg3sonc3wyskcbkoi93lhdoor)
- [reference materials]
   - Podcast design reference
   - Audio player research
   - Audio player collaboration notes

#### Acceptance Criteria
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by oliviaflory** [comment]
Meeting scheduled with Kaltura team for Jan 20, 2021
