### ISSUE TITLE
Audio player: Final design 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#164]
Reference Olivia's and Jame's existing work on Audio player, conclude this work with cleaned up design proposals for MVP and potential wedding cake versions. 

### Acceptance criteria 
- [x] Final MVP design proposal
- [x] Future state proposal
- [x] Meeting to deliver to stateholders

**Comment by photodow** [comment]
[Here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4866#issuecomment-779279790) is an update from some of last week's work on this https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4866#issuecomment-779279790

**Comment by shixiedesign** [comment]
Another piece of info https://cognitive-app.slack.com/archives/GBG66T9NK/p1613671614140900

**Comment by shixiedesign** [comment]
Final design recommendations: 
https://ibm.box.com/s/5tb82n71maykwdkw1shvxbeg7fpyptff

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/562bb4b6-c334-46ca-b5b8-9b123f3caa1b)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/4974b419-6b57-4d7d-b900-cf3309287806)![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5407c46f-0101-4372-9f08-fa5352caa0e9)![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/88f79d51-0a5c-45f6-9c42-12bdba110bae)
