### ISSUE TITLE
Back to Top: Research and Design:  Target Nov 30, 2020

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#166]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

### Notes
- Are there designs we can use? Like Gatsby
- Relationship with UMX Let's talk button and placement (center? left?)
- A11y related
- How does it interact with the content under it? Translucent? Fades out on pause?
- Behavior: does it show up after scrolling? Or at the end? After a pause?

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Research findings are available in the above Box folder
- [ ] The next story has been updated with the research findings
- [ ] Final designs are available
- [ ] Design spec issue has been created on the Agile board with the documentation needed and the work scheduled.

**Comment by RobertaJHahn** [comment]
Ideation work is scheduled for sprint 20-23.  Target to move to Agile board sprint 20-24.

**Comment by photodow** [comment]
Here are the designs and functional specs for here.

https://ibm.ent.box.com/folder/127553793291
