### ISSUE TITLE
Anchor Link: Hybrid Cloud anchor links component design study: Target - sprint 20-25

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/digital-design-ideation#172]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder](https://ibm.ent.box.com/folder/125209461240)
- [reference materials]

#### Acceptance Criteria
- [x] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by oliviaflory** [comment]
I shared with Shawn H that we are looking to add the Anchor link to our library, his team is currently running an A/B test with an updated Anchor link pattern that better aligns with the Table of Contents component. 

>the first test is the whole page. It's being done with a clickable prototype so we will be doing one later with a focus on the nav component later when we have a coded version. I'd say proceed as needed but just have this on your radar for now. We expect to have results from initial testing by end of month 

Link to [Slack conversation](https://cognitive-app.slack.com/archives/GVAG3EPDG/p1607546787162000)

**Comment by RobertaJHahn** [comment]
We will wrap up this work and keep the final design story in the first sprint in Jan.
