### ISSUE TITLE
Ideation on how to present IBM.com Style models detail per model on website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#181]
### Objective:
Our current [Style Model page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/style-models/overview) under the Guideline section provides high-level information about the style models. However, each model needs to include the following details, so we need a way to present the model details on Carbon for the IBM.com website.

- Detailed description of the user intent
- Primary grid usage
- Secondary grid usage options
- Color themes
- Type scale
- Spacing
- Shell
- Common page types
- Examples
- Starter Kit

### Possible steps

1. Meet with Wonil to understand the potential content required for each item listed above.
2. Do a quick study on how other websites similarly treat the content organization.
3. Set up the Mural board to ideate on possible ways to take care of the page structure and IA.
4. Align on the direction and confirm with the development team on possible restrictions for Gatsby's theme.
5. Align the timeline and priority with Linda and Jeff.
6. Create individual task issues for publishing.

### Acceptance criteria

- [ ] Have a clear plan on what each page are going to include.
- [ ] Have an aligned vision on how the IA set up is for each of the models.
- [ ] Create individual task issue for publishing on Agile board.

**Comment by JennySanchez** [comment]
@wonilsuhibm The IBM.com style models detail can be viewed on the [Style Models list tab](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/style-models/style-model-list). Can we close this ideation issue or is this for the future iteration beyond the MVP version?

**Comment by ghost** [comment]
@JennySanchez This is beyond the MVP.

I have three models presented in this [prototype](https://ibm.invisionapp.com/share/5BO0RUM3VMQ#/319811727_Model-1).

### Model 1
The style model list page is one long page. The height will reach 50,000 px, which feels a bit too tall and not scalable.

### Model 2
Each style model has a hidden detail page that is access from the list.

### Model 3
The list page shows some level of details, the way it is currently, but each style model has a linking mechanism (button, card, link, etc) that opens the associated hidden details page.

The sketch file is located in Box [here](https://ibm.box.com/s/86suoey2doz8md0atqie15r68p6dpflg).

**Comment by JennySanchez** [comment]
Thank you for sharing the style model list nav ideas with me, @wonilsuhibm. As mentioned, Model 3 works the best but we might want to take a look at the "back to the list" link treatment as a group Friday.

**Comment by RobertaJHahn** [comment]
@shixiedesign Trying to do some clean up.  This task is in the current sprint and assigned to Wonil.  What would you like to do with it?

**Comment by JennySanchez** [comment]
@RobertaJHahn You can assign the issue to me, and please remove the priority: high label and take the milestone off.
Wonil wanted to work on it before leaving, but he did not have time to work on it. We need to get to it eventually, but it's not urgent. I am working on getting all the task issues in one place and take another look at the things we need to work on for the website with DDS Leads.

@shixiedesign Let me know what do you think?

**Comment by JennySanchez** [comment]
This task issue is no longer relevant to our work or priority and will be closed.
FYI: @RobertaJHahn
