### ISSUE TITLE
Scroll animation: slide up & down - Target sprint 20-24

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/digital-design-ideation#182]
Design an addition to the scroll animation utility that allows adopters to enable sliding up and down for a given component as the user scrolls down the page.

#### Resources
- Scroll animation [[box](https://ibm.box.com/s/s51j07ltae5gr31km38q6no1jfnadlgw)][[codepen](https://codepen.io/photodow/full/vYKaaxK)][[research](https://ibm.box.com/s/mauojg9vq6ordwbtxcb2g0ihbrj3hplq)]
- Scroll into view [[box](https://ibm.box.com/s/4d0l5zddtjdwpkpo3tj34e0ipmpeyj7u)]

#### Acceptance Criteria
- [ ] Explorations complete
- [ ] Designs complete

**Comment by RobertaJHahn** [comment]
@photodow Is this work finished?  Can you post the links and update the status as well.  Thanks.

**Comment by photodow** [comment]
@RobertaJHahn here is the link. Got a couple of rough edges I need to iron out, but I can move into review.

https://codepen.io/photodow/full/vYKaaxK

**Comment by RobertaJHahn** [comment]
@photodow Could you post links to the designs into this issue and the epic (#4766) so the dev's know what changes have to be made?  I'd like the issue to be complete before closing.  Thanks.

**Comment by photodow** [comment]
@RobertaJHahn I posted the link to the designs via the prototype before the break. The functional specs should have more details for the devs similar to how we did the fade animation.

**Comment by RobertaJHahn** [comment]
@photodow Your comment above with the prototype link says that some more work is remaining.  A comment stating that the designs have been approved and moving this issue to done, would make the status clearer.  Thanks.

**Comment by photodow** [comment]
@RobertaJHahn because @wonilsuhibm hasn't approved it. Right now he's taking a stab at trying to get a specific aspect of it to work the way he wants. I'll let him update from here.

**Comment by RobertaJHahn** [comment]
Wonil and James agreed in the Design meeting that this issue can be closed.
