### ISSUE TITLE
Card audit

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/digital-design-ideation#184]
Our adopters are continuing to have a greater desire to have more variations for our cards. We should go through our existing cards, proposed cards, and potential known variations and see how we can better meet our adopter's needs in a more systems way of thinking.

##### A couple of things we may want to consider:
 - typography and content hierarchy variations
 - icon, media, and pictogram placement
 - Spacing variations
 - Interaction variations (static, link, hover show/hide)
 - size variants (section, block... )
 - aspect ratio variants
 - defintion, documentation/guidelines
 - content model variations

##### Things to reflect on:
 - Existing cards
 - Proposed / work in progress cards
 - Cards being used across IBM

**Comment by JennySanchez** [comment]
@photodow @RobertaJHahn I added the "Design" and "Design Study" to this task issue but not sure if they are the correct label or if I miss anything. Can you take a look? Thanks!

**Comment by RobertaJHahn** [comment]
We should review this issue in the Dec 3 meeting with the team.  I have added it to the agenda because the issue doesn't have the labels that we normally filter on.  thanks for sending the message.

**Comment by JennySanchez** [comment]
Perfect. Thank you, @RobertaJHahn !

**Comment by RobertaJHahn** [comment]
Closing,  Will create a new issue when the work can be scheduled.
