### ISSUE TITLE
Mobile design studies

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#22]

**Comment by JennySanchez** [comment]
@wonilsuhibm @oliviaflory Can you help by providing a bit more information about the task? 

Such as...
- Objective or the expected outcome of the design studies
- Any existing material to help assignee understand the needs or get started faster?
- Any recommended steps to take?

**Comment by RobertaJHahn** [comment]
Closing as the issue is not complete and old.
