### ISSUE TITLE
Locale change banner: mobile prototype for testing

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#25]

**Comment by jacobottesen-dgc** [comment]
cc. @wonilsuhibm @oliviaflory 

Prototype has been designed in Adobe XD. One problem is that our XD licensing doesn't allow for prototype link sharing. Is there a way we can update that?

![Screen Shot 2020-05-06 at 11.38.30 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/92165d23-0338-442e-87ec-3a5811339c2e)

**Comment by jacobottesen-dgc** [comment]
Mobile prototype can be found in Box: https://ibm.box.com/s/3i7gpdmerk7rjbtygcgy1fx5xewkgdpp
