### ISSUE TITLE
Locale change banner: desktop prototype for testing

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#28]

**Comment by jacobottesen-dgc** [comment]
Desktop prototype is finished and ready for testing. 

![Screen Shot 2020-05-06 at 11.49.02 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/c4995255-0d7e-4581-a8ea-64f4dcd5f6b9)

**Comment by jacobottesen-dgc** [comment]
Desktop prototype can be found in Box: https://ibm.box.com/s/qhjwzxl72ex1a0kgq653fmspe1vgts4v
