### ISSUE TITLE
Error page redesign

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#32]
#### User story
As a user of IBM.com, I need to be informed of an HTTP error and understand what the next steps are.  The error pages were implemented on v18.  This work is needed for Carbon.  

#### Notes
_Original issue: https://github.ibm.com/webstandards/digital-design/issues/293_
- Moved this issue from the agile board (https://github.com/carbon-design-system/ibm-dotcom-library/issues/190)

#### Next Steps
- Research
- Design exploration
- Design
- Review & approval
- Development
 
#### Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

**Comment by RobertaJHahn** [comment]
_On Aug 13, Wonil-Suh1 commented:_
![error-page--current--404](https://media.github.ibm.com/user/25726/files/8aa70a80-bda4-11e9-9ac9-ce1dc6a19860)
![error-page--current--xxx](https://media.github.ibm.com/user/25726/files/8aa70a80-bda4-11e9-8de4-83ff2fa98a84)

**Comment by RobertaJHahn** [comment]
Olivia commented On Nov 25, 2019:

<img width="1680" alt="Screenshot 2019-11-25 at 18 24 34" src="https://user-images.githubusercontent.com/45692622/69565889-d95b6780-0f83-11ea-9ae4-9bd9b7d9a158.png">

couldn't manage to reproduce this one, so only have the screen shot.

**Comment by shixiedesign** [comment]
Lots of great content here. Moved over to the https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5976 and this can be closed.
