### ISSUE TITLE
Review and evaluate patterns (taxonomy, ontology, documentation)

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/digital-design-ideation#33]
### Problem to solve

There are many people from DDS and Reboot working on patterns. There are misalignments and misunderstandings of how different aspects of patterns work or should work. 

### Objective

This epic will capture the various things that need to be addressed in order to align people around patterns, evolve the ontology, and support our adopters in the best way possible. 

### Core team members

- Lara Hanlon
- James Dow
- Kenny Lam
- Shixie Trofimov
- Wonil Suh (DDS / Reboot lead)
- Jeff Chew (DDS lead)

### Contributors 

- Lila Title
- Seth Carnes
- Olivia Flory
- Linda Carotenuto 

### Additional info
See [Box folder](https://ibm.ent.box.com/folder/83745317622) for resources, links, designs and other useful files.
- Black Theme Masthead issue on the Agile board is dependent on this design work.  Once the design decisions are made, the dev work can move forward.   [Issue #2791](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2791)

**Comment by larahanlon2** [comment]
Met with James, Kenny, and Shixie today. We discussed next steps for patterns work and agreed on the three core buckets of work: **Ontology, Organization and Taxonomy, Documentation.** 

<img width="1298" alt="Screen Shot 2020-05-18 at 1 29 30 PM" src="https://user-images.githubusercontent.com/53093550/82242510-f86ffc00-990b-11ea-8065-521cc49e0ac8.png">


### Next steps:
1. Shixie set up time to continue ontology learning and exploration session 
2. Lara will share #46 during review meeting on Tuesday 
3. Lara set up a working session to evaluate subpatterns 

### Considerations
- We need to do a gap analysis of ontology before making fundamental changes
- Documentation is dependent on ontology and organization 
- Need to pull Jenny into the documentation step for website
- We are serving many different users. Do we understand their needs?

**Comment by larahanlon2** [comment]
Added 3 Box folders for these work items under [Anatomy and Foundation](https://ibm.ent.box.com/folder/83745317622).

**Comment by shixiedesign** [comment]
`Pattern` will continue but not via this epic. 
For now, FYI @janchild please see Lara's past work on Pattern https://ibm.ent.box.com/folder/83745317622
