### ISSUE TITLE
Planning: IBM.com Style Model page content and IA

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#37]
@JennySanchez commented on [Mon Apr 13 2020](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/389)

> As an IBM.com Library website creator, 

> I need to have alignment on what content will go into the uIBM.com Style Model page and how the reference link linking strategy will look like with Wonil

> so that I know how to move forward with the content crafting.

#### Additional information

The Mural.ly board used for discussion can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94).

#### Tasks
- [x] Discuss with Wonil and find out details needed

#### Acceptance criteria
- [x] Have a clear idea of what we will have and set up the IBM.com Style Model page.

**Comment by wonilsuhibm** [comment]
A quick thought on the organization of the style model section on a [Mural board](https://app.mural.co/invitation/mural/wonilsworkspace4185/1590001834805?sender=wonilsuh19286&key=3fa4f652-2885-41df-b011-10b953d485bc)

**Comment by JennySanchez** [comment]
Work session scheduled for 08/04 (Tuesday) 12:30 pm CT.
focuses:Get a better idea of the IA and what to publish in Sprint 20-16.

**Comment by JennySanchez** [comment]
**Note:** Once the planing is done, we will do the MVP version of first IBM.com Style Model page via task [#575](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/575).

**Comment by JennySanchez** [comment]
Based on the discussion today, we will create a "Building for IBM.com" guideline page under the Guidelines section on the [website](https://www.ibm.com/standards/web/ibm-dotcom-library/).

On the "Building for IBM.com" guideline page, we will four areas of focus for the content crafting.

1. Introduction and Vision.
2. IBM.com shall.
3. Intro to style models, definition, background, etc.
4. List of design intents and their style models.

The "IBM.com page structure" will be the 5th priority to be added to the guideline. 
The structure of the page, for now, will be determined by the amount of the content. For example, we might utilize the in-page tabs for the content organization or break content out to its own website page.




---
Planning detail can be viewed on the IBM.com style model content structure [Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1596643950626?sender=chsanche&key=f3dad220-1994-47ad-a8ad-64e6e13af413).

![Screen Shot 2020-08-11 at 5 34 24 PM](https://user-images.githubusercontent.com/45213839/89955574-f1017b80-dbf8-11ea-9b17-06fa05bc0fbf.png)

---
@wonilsuhibm Please let me know if I missed anything. Thank you.
