### ISSUE TITLE
(MVP version) Content strategy for Layout Patterns section on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#40]
### User story
~~As an IBM.com maker, I would like to understand how to use any specific pattern layout the right way~~.

As an IBM.com library website contributor, I need a way to set up any website page for a layout pattern, so that our adopter can see a cohesive structure across the Layout Patterns section and find information intuitively and efficiently.

FYI: @larahanlon2 @sethibm I updated the user story originally crafted by Wonil, let me know if it works for you and if you have any questions.

### Additional information
- [Leadspace sample page](http://ibm-dotcom-library.mybluemix.net/patterns/leadspace/)

### Tasks
1. Collect adopter needs and pain points around layout pattern usage (#43)
2. Compose a list of information necessary for component guidelines
3. Identifying the essential pieces of information for MVP publishing (#20 )
4. Creating a content template wireframe

### Acceptance criteria
- [x] Content template wireframe is available for use in the template update story
-  [x] Prioritized list of patterns to be published is available

**Comment by RobertaJHahn** [comment]
@JennySanchez  how to use the layout component should be included in the Development Documentation guidelines section of the website.

**Comment by JennySanchez** [comment]
@RobertaJHahn I am not sure what you mean?

What we are looking at here is the strategy for creating a pattern page on the website and around what a particular pattern is, how to use the pattern in a scenario, and the development section typically looks like the screenshot below, if you like, please see the [Lead Space page](https://www.ibm.com/standards/web/ibm-dotcom-library/patterns/leadspace) as an example. 
![Screen Shot 2020-06-04 at 9 34 11 AM](https://user-images.githubusercontent.com/45213839/83770369-9a9b1e00-a646-11ea-9867-1ef1f34c7923.png)

**Comment by JennySanchez** [comment]
@larahanlon2 @sethibm As mentioned yesterday, all the material shared via the Mural boards from #43 and #20 is available for you. Please see the Acceptance criteria section above for task expectation and let me know if you have any questions.

**Comment by JennySanchez** [comment]
Hi @larahanlon2 We have the MVP template, published criteria, and priority all on the [IBM.com Library Publishing Criteria and Priority Planning Mural board](https://app.mural.co/invitation/mural/ibm14/1592586700298?sender=chsanche&key=0f7c3917-398c-4fc0-a429-ebe8667b20ad) for discussion.

Please let me know if there's anything else we need to work on for now. Otherwise, I'd like to move this task issue to the "Done" column. I know each Pattern might require different content structure for it to make the best sense for the adopters. As we go, I'd like to continue creating series of Sketch templates based on the intents or needs so we can have a complete overview of the content needs by the end of 2020.

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil. We are good to close this task and we will work on the next iteration of the strategy via #104 .
