### ISSUE TITLE
IBM.com navigation design

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/digital-design-ideation#45]
### Objective

Reboot IA team are working to improve the navigation for ibm.com. They require support from DDS and Reboot designers to apply Carbon, IDL, UX and UI best practices to the navigation models they are proposing.

### Additional information

- Wonil and Lara worked on ibm.com navigation components in 2019/20 including masthead and footer.
- Since Q1, Wonil and Lara have been meeting with Keegan Whitla, Colleen Corkery, and Elliott Trice to review new IA models for global masthead.
- Reboot team are working on updates to L0 and introducing a new mega menu.

**Comment by ghost** [comment]
Let's close this epic. All tasks were done, now we have moved to the next phase.
