### ISSUE TITLE
Mega menu design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#52]
### user story
As a user of IBM.com, I'd like to navigate in a way where I can have an eagle's eye view of all that is available and identify what I am looking for.

**Comment by wonilsuhibm** [comment]
### Nielsen Norman Group
https://www.nngroup.com/articles/mega-menus-work-well/

### Type of megamenus
https://siteiq.net/16505/best-practice-5-mega-menu-styles-and-the-12-sites-that-do-it-best

**Comment by oliviaflory** [comment]
Research readout recording: https://ibm.ent.box.com/notes/680941516790
