### ISSUE TITLE
Website traffic tracking (As-Is) tooling research

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#53]
### Objectives
This task is to understand the current (As-Is) Website traffic tracking methodology and what impact it brings to the growth measurement of the website.

**Comment by JennySanchez** [comment]
(05/19)

- In the past, we used Hotjar for NPS tracking then add the outcome into an [Excel document](https://ibm.box.com/v/DDS-Heatmap-Summary) and the process is fairly complex (see reference below).

![Screenshot_2020-05-19 DDS Hotjar Heatmaps xlsx Powered by Box](https://user-images.githubusercontent.com/45213839/82338319-5d7e2d00-99b2-11ea-8632-51bc19efe0ff.png)

- The Carbon Team is using [Fathom](https://app.usefathom.com/share/vmsgxqrs/carbondesignsystem.com#/?from=2020-04-21%2000%3A00%3A00&site=2285&to=2020-04-28%2023%3A59%3A59) to collect data on the Carob Website.

![Screen Shot 2020-04-28 at 4 00 49 PM](https://user-images.githubusercontent.com/45213839/80537316-73776f80-8969-11ea-97ac-7ad7442b90fc.png)

**Comment by JennySanchez** [comment]
**Note:** Followed up with Matt on Thursday (06/11), even the Carbon Team is using Fathom to collect data on the Carob Website, he found the tool is not meeting the need but seeing which page has more visitor and they might move back to Hotjar.

**Comment by JennySanchez** [comment]
**Note:** Adding the [Hotjar Survey](https://insights.hotjar.com/sites/42920/polls/responses/506324) we are using currently (08-20-2020) here.

![Screen Shot 2020-08-20 at 3 27 36 PM](https://user-images.githubusercontent.com/45213839/90822314-d8c8e500-e2f9-11ea-8ab8-8621877cde2f.png)

**Comment by RobertaJHahn** [comment]
Google Analytics is being used.  Reports are being created weekly.  Closing
