### ISSUE TITLE
Create publishing criteria for Patterns and Components website pages

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#55]
### Objective

The website stream is working on the content publishing roadmap for the website so we know what content we are going to publish. Even we have a list of the patterns and components (see below), it requires prioritization criteria from the stream leads (Olivia for Components and Lara for Patterns) **so we know what we can consider as "ready" for content crafting and placed in an upcoming sprint for publishing.**

**Components** 
![Screen Shot 2020-05-23 at 11.09.42 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/2a088b90-05e6-42f2-b14a-0b81654582b5)

**Patterns**
![Screen Shot 2020-05-23 at 11.10.05 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/773c43d6-762f-44e5-a0b4-5fdc8c5af5fd)

**Comment by JennySanchez** [comment]
@oliviaflory @larahanlon2 FYI on this task existed. If you have prioritization criteria in mind already, please feel free to add it here.

**Comment by oliviaflory** [comment]
### Components
Here is my first take on it based on the list and mural from before.

1. Table of Contents _(TBD component or pattern)_
2. Locale selector / modal  _(I don't really think this is important considering no one is using this yet, but saw it had a star from Linda or Wonil, so left it here)_
3. Link with icon 
4. Video player _(I see a LOT of questions about this one on our channels, it would probably be helpful, I think it's stable now)_
5. Lightbox media viewer
6. Horizontal rule 
7. Link list (new)
8. Expressive modal
9. Locale notification _(not completed)_
10. Image with caption _(do we want to surface this?)_

**Comment by JennySanchez** [comment]
Hi @oliviaflory Prioritization criteria I am looking for is the list of criteria we need to have and meet in order to say "Yes, we are ready to work on the content for this X component to be published on the website". For example, it needs to be React code ready, it needs to pass the QA by the QA team, or it needs to be reviewed by the Cabron team).

**Comment by JennySanchez** [comment]
@larahanlon2 I am glad we get to touch on the expectation of this task. Please let me know if you have any further questions or if you need anything to start the task.

**Comment by JennySanchez** [comment]
**Note:**
- For Components, We ONLY publish the components that is "ready to be used".
- For Pattern website pages, MVP could be as long as the Pattern design is approved by the stakeholder.

**Comment by JennySanchez** [comment]
👉  **Components and Pattern publishing criteria** [BOX document](https://ibm.box.com/s/y3r76vpk0dem15o8d80w53r9dyuy8bvq) created for the list and collaboration.

**Comment by JennySanchez** [comment]
@wonilsuhibm Components and Patterns publishing criteria is ready for review. You can view them via 1. [BOX document](https://ibm.box.com/s/y3r76vpk0dem15o8d80w53r9dyuy8bvq) or 2. [Mural document](https://app.mural.co/invitation/mural/ibm14/1592586700298?sender=chsanche&key=0f7c3917-398c-4fc0-a429-ebe8667b20ad).

Let me know if you have any questions.
