### ISSUE TITLE
Login page (URX) design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#57]
### Objectives
URX team is looking into updating their current login page design, inspired by the Cloud login page and Carbon login patterns.

### Notes
These are from the URX team:
Current URX/IBMid Login Experience: https://www.ibm.com/account/reg/us-en/login?formid=urx-19776
Work in Progress: https://pages.github.ibm.com/dgc-web-platform/login-ui-carbon/

**Comment by RobertaJHahn** [comment]
This work should be done by the Guild process or a a DGC resource requested through Nigel.  Closing.
