### ISSUE TITLE
IBM.com Library : Pattern and Template Inventory

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#58]
As discussed, this is to support the following two audience groups:
- Executive stakeholders
- Content strategists (there are new content strategists who need to know what patterns exist, and this need is immediate)

The plan
- Create a single page Invision prototype with three sections:
   - Section 1: collection of all top level patterns, each linked to the corresponding storybook page
   - Section 2: Learn page template mapped to the patterns
   - Section 3: Solutions page template mapped to the patterns

Follow-up work
- Adjust Sketch and Invision template to the grid and matching IDL and Carbon specs

LATEST PROTOTYPE:
https://ibm.invisionapp.com/share/DJO051VE7X2

**Comment by sethibm** [comment]
Iteration #1 of this project had two options, one with all project goals on one artboard in Sketch (also Invision), the other building a UI setup and navigation across the three key areas.  Seth and Wonil reviewed both and picked UI setup.  

Currently wrapping up iteration #2 of the Invision prototype and will share with Wonil, ideally share with team asap for input, feedback.

**Comment by sethibm** [comment]
- Iteration 2 and 3 completed, shown to Wonil and then DDS team.  Changes included adapting all spacing, type and icons to IDL / Carbon, because the UI framework is from a design used last year for IBM Industries

- Showed iteration 2 on Sprint Review meeting 6/9.

- Currently showing iteration 3 to Reboot team, collecting comments in Invision and communicating on Slack towards a next iteration.  

- Will show iteration 3 or 4 on DGC Design Crit meeting this afternoon

**Comment by sethibm** [comment]
- Iteration 4 and 5 complete.  Included full review of all comments from first round of input from DDS and Reboot teams.  Design changes included removal of top black and grey bar backgrounds and column names for "Variations" and "Notes" 

- Waiting on input from @photodow re: pattern naming and functional analyst perspective.  

- No input from developers yet, but Jeff is aware and asked questions about whether this would translate to IBM.com Library website or need coding from dev side.  Answer currently on both: no.

- Pending work: 1) review and confirm all relevant patterns are shown 2) Review relevant notes, especially knobs to help guide or show readers towards pattern variations that are available

**Comment by sethibm** [comment]
- Found out today some links in the prototype are not going to the correct Storybook version of pattern.  Going to update.

- Also trying to deep link to pattern variations shown on Invision, but cannot currently.  Devs showed how to Copy code so it plugs in variables within the browser, but Invision says this kind of URL is invalid.  Logged support request with Invision to help solve

- Also finishing up review of Knobs / variations of patterns, to be sure they are usable on Storybook.  Logging any related bugs.

**Comment by sethibm** [comment]
@wonilsuhibm Fyi, all links in this prototype are now updated to the latest Storybook, after some chats with devs to make sure they are correct.  LeadSpaceBlock and LogoGrid are the only ones remaining to update, which can happen later today (waiting on v1.8.0 to publish with them).  

Otherwise it's up to date and can continue to be shared.  

Only other thing is minor...dealing with Invision to see if they can enable links from Storybook with variables, so we can link people direct to Leadspace Centered for example, or any pattern where Knob is auto selected to a certain view of a pattern.

**Comment by sethibm** [comment]
Finalizing update plan with this prototype with Wonil, and input from other designers on DDS and Reboot, towards IDL and Carbon, and will do asap.

**Comment by sethibm** [comment]
@wonilsuhibm Update: powering through as quick as possible.  Taking longer than estimate. 
The resizing of all patterns looks good in 1312, but there are added steps and time, especially with varying patterns being different widths and percentage export / scaling with Sketch is not ideal.

The Patterns page is finally done, though there may be some of the newer patterns that will need to be added.  Remaining todo: Finish tagging Learn template and Solutions (just the more complicated, long patterns shown on them).  I think it will be done tomorrow for sure, and can send for review / comments from team, and switch to publishing while that happens.

**Comment by sethibm** [comment]
Latest prototype link shared with DDS for input / comments / feedback.  Will share with Reboot next.

**Comment by sethibm** [comment]
Updated CTA section, Content group horizontal, Callout with media to Guidelines links.

Logged Lila's input / suggestions for copy change on component descriptions within Mural Web Publishing Triage document for now, until team confirms where these discussions and final copy decisions will occur:

https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1596216481914/86a1304ba4b3b616e89738e5813215f8cd021dbe

**Comment by sethibm** [comment]
@wonilsuhibm Can you take a look at this update and share thoughts on moving forward? I've tried to ping on Slack but the channels and threads were in flux last week.  

https://ibm.invisionapp.com/share/PZO0B7BAXVB#/319655941_Patterns

This shows all existing patterns in the Pattern Inventory updated, so they are all placed in context of IDL grid / columns, using 1312px breakpoint.  This was started from Linda's comment earlier in the week when presenting the latest inventory, then continued, as it matches up to decision flow on how images will be made and placed on the website.

Please note, for Table of contents and Link list, also Lead space block, I kept other components in there, but faded them at 10% opacity, as it seems helpful for contextualizing those components, as user flows down the screen in Invision (see attached examples, also shown in Invision link).  This is related to Link list work from Jacob, but also overall conversation on how to handle hero images for components, so end users can absorb context of how they work, and where they sit on the page (ie 928px images), versus specific specs and details which might help to show in smaller images (ie future 608px)

I have not yet scaled these down to the 928px versions that would be placed onto actual inventory page, as feedback is needed first, if this looks good to go for this purpose.  These can also be used for web publishing, at least some of them, as I've made a few versions that are not in the visual specs but appear on Storyboard.

Also, this is a relevant short study from two weeks ago, around image sizes and functionality, related to 928px vs 608px options:

https://ibm.invisionapp.com/share/3HO0AND9GJN#/319641775_Pattern_Pages_-_Sample_Image_Sizes

So, with TOC and Linklist for example, we could have a hero image or several heros that show them in context at 1312 (928), and then drill down to just the component itself within a 608px image.  

I think we only need to decide on hero 1312 (928) pixel image to use now for all of these, on both this inventory and for web publishing, and can arrange a meeting to discuss 928 vs 608 images meanwhile?  

cc @JennySanchez

**Comment by sethibm** [comment]
@wonilsuhibm @ljcarot Fyi, I've updated this Invision prototype for the Patterns and templates.  

Linda, the comment and idea you shared about trying to show patterns as they appear in IDL grid and columns when this was shared in a presentation had broad impacts across all imagery being published on the website :) It also helped speed some of the work up, as I was already working on making graphics in this style when it was decided to do the same on the site.  

At the moment, almost all the components shown in this prototype are published on the website, except Link list (likely will go live tomorrow) and Content block — mixed groups.  There are other components and patterns to be published still, but they were not included in this prototype yet, as it mainly captured the key ones visibly shown in the templates.

The remaining helpful aspect of this prototype is seeing many patterns / components at once, and seeing how they appear within sample templates (both not yet available in the current website).  

cc @JennySanchez @jacobottesen-dgc

**Comment by ljcarot** [comment]
Great work and thanks for the update!!
