### ISSUE TITLE
Release the Early adopter starter kit

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#64]
#### Objective

The website stream is developing the Early adopter starter kit. We need to make release announcements so adopters can start using the kit.

#### Tasks
- [x] Go over the kit with the team
- [x] Make announcements for adopters to use the kit.

**Comment by JennySanchez** [comment]
@wonilsuhibm Jacob mentioned [the Adopter Kit](https://ibm.ent.box.com/folder/116567620037) is ready. My thought is we will add a section in the [Get Started Overview page](https://www.ibm.com/standards/web/ibm-dotcom-library/get-started) and provide a link to Git for adopter kit access requests or we can add a card to the "Resource" section and link to Git for adopter kit access requests.

What do you think?

FYI: @jacobottesen-dgc

**Comment by ghost** [comment]
Hi Jenny, what you proposed sounds perfect to me. Please go ahead.

**Comment by JennySanchez** [comment]
The next step will be worked on via #610 on the Agile board.
https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/610
