### ISSUE TITLE
Explore the meaning of ontology

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/digital-design-ideation#65]
### Problem: 

- The word ontology is causing confusion between DDS team members and adopters.
- This finding has been surfaced in multiple conversations and collaboration sessions.

### Goals:

1. Understand how team members and adopters understand the word ontology.
2. Identify where we are using the word ontology in our process.
3. Explore a solution: do we need to replace the word? Do we need any word?

**Comment by larahanlon2** [comment]
James, Kenny, Shixie and I have been having ongoing discussions and working sessions to understand and evolve the ontology. **A continual pain point that keeps coming up is that we (and other team members) do not have a clear understanding of the meaning of ontology or why we need this term.**

Examples of pain point and ideation findings:
<img width="665" alt="Screen Shot 2020-06-02 at 12 57 59 PM" src="https://user-images.githubusercontent.com/53093550/83547787-bbd9fe00-a4d0-11ea-836f-ec51cdfda396.png">

<img width="571" alt="Screen Shot 2020-06-02 at 12 58 44 PM" src="https://user-images.githubusercontent.com/53093550/83547859-d4e2af00-a4d0-11ea-84d5-539e1fac1192.png">

Feedback from team members and adopters can be found in [this Box note](https://ibm.ent.box.com/notes/673303121522).

**Comment by larahanlon2** [comment]
### Alt names we explored to replace the word ontology:
1. Anatomy
2. Frame
3. Foundation
4. Structure
5. Assembly
6. Functional framework

### Current point of view:
After review of all known process documents for DDS and Reboot team, interview with team members, review with the patterns core team (James, Shixie, Kenny, Lara), **we are proposing to remove the name ontology with no replacement.** 

### Advantages of removing the name completely:
1. Ontology sounds like oncology. Removing the word would remove this association.
2. It is not a commonly used word in the design industry.
3. Education is required to explain the meaning of the word.
4. Time is needed to document and define the word in the context of DDS and ibm.com library.
5. It continually surfaces as a blocker and point of confusion for team members and adopters.
6. Carbon does not use any similar word.

**Comment by wonilsuhibm** [comment]
Thank you. 

Re removing ontology completely, one question—in the new structure/organization of patterns and components, is the act of defining relationships between things still necessary? If so, I'd suggest that we still give it a name. Currently, that ontology process is a necessary step and needs to have a name because it needs to be incorporated into plans.

Replacement: functional analysis sounds in the right direction. But it sounds like it's representing more than just functional analysis. Functional analysis in most cases does not include design. Can it be a bit more generic, like pattern analysis?

**Comment by larahanlon2** [comment]
As agreed by the majority of the team including Linda and Jeff (and Reboot), we are going to try and stop using the word/term ontology. We will refer to the steps as they are eg. design review, patterns design planning, dev review, functional analysis. If we find that we need a replacement word we are considering **pattern analysis**.
