### ISSUE TITLE
Footer v2

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#69]
### User story
As an IBM.com user, I would like to see what else is available on IBM.com once I finish consuming the content of a page.

### Notes
We have a footer design that we inherited from Northstar, but the content is a few years old and the specific requirements are not clear at the moment. This epic is to look into the content, requirements, and potential solutions if necessary.

**Comment by shixiedesign** [comment]
Close coz duplicate
