### ISSUE TITLE
IBM.com Library Pattern Naming Issues

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/digital-design-ideation#71]
There are issues with pattern naming that Seth and Shixie have noted, and likely need resolution asap, handling downstream effects on code side, and to update and / or create the source of truth and guidance document for IBM.com Library Naming. 

Key issues:

- In code, some patterns use Title Case (with spaces) and others use CamelCase (no spaces).  This needs to be universal, as one or the other.  

- There is request for a "human naming" version from Linda, for use in Pattern and Template Inventory Invision prototype. Needs review / discussion per notes below, and can then update the prototype if needed.

TITLE VS CAMELCASE

Examples of "Title Case" (with spaces):
Table of Contents
Expressive Modal
Link with Icon 
Simple Benefits

Examples of CamelCase (no spaces):
ImageWithCaption
VideoPlayer
ContentBlockSegmented

HUMAN NAMING

- Do we need an equivalent "human naming" for some usage, while using coded pattern name other times?  
- Is it easier to maintain a universal name and syntax for the pattern, for how we call and write them everywhere?  
- If using two naming types, it will need guidance within source of truth for when each name type is used.

SOURCE OF TRUTH

Linda notes there is a naming document as an Airtable as the source of truth.  

- Is this the document to use as source of truth?
- Does it include and can handle guidance on naming, for anyone who has a question?

DOWNSTREAM EFFECTS

- What are the downstream effects after naming convention is decided, as far as changing the names in the code, for Drupal and other adopters?  

LINKS

Experimental Storybook:
http://ibmdotcom-react-experimental.mybluemix.net/?path=/story/overview-getting-started--page

Deploy Storybook:
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1699/index.html?path=/story/overview-get-started--read-me

Airtable:
https://airtable.com/invite/l?inviteId=invy1LEJDPntmc6yr&inviteToken=fd9221a8a9350ef3e1a7776e685e7547233d3f2630b0d10bce6b42c4ccddf835

**Comment by sethibm** [comment]
@ljcarot @wonilsuhibm @shixiedesign 
Notes looking at Airtable compared to Storybook Experimental (where the most of the current patterns sit):

**Link with Icon**
Not shown in Airtable.  In Title Case for code name, should be CamelCase?

**Expressive Modal**
Not shown in Airtable.  In Title Case for code name, should be CamelCase?

**Locale Modal**
In Title Case for code name, should be CamelCase?

**Table of Contents**
In Title Case for code name, should be CamelCase?

**Dotcom Shell**
Not shown in Airtable. In Title Case for code name, should be CamelCase?

**Simple Benefits**
Not shown in Airtable. In Title Case for code name, should be CamelCase?

**Simple Overview**
Not shown in Airtable. In Title Case for code name, should be CamelCase?

Thoughts?

**Comment by RobertaJHahn** [comment]
Naming cleanup is underway as part of the Housekeeping epic.  (#5321)
