### ISSUE TITLE
DDS Source of Truth | Design + Dev

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/digital-design-ideation#78]
### Objectives
Create a singular source of truth document for DDS team, that can be used for onboarding any new team members, and allow current team members one location where all relevant, key links to team organization, Storybook, Zenhub board, folders, box files, etc can be found and used.

**Goals**

- Reduce confusion 
- Reduce time spent looking for links, folders and documents
- Clarify team members and roles as they evolve
- Help new team members onboard quicker

### Notes

- A new folder was added called "Source of Truth" on DDS Squad Box folder
- A Box note was created called "DDS Source of Truth"
- A first version will be drafted, then team members can input into this evolving document

### Problem

- There are a multitude of folders, files, links, channels, and processes between DDS and Reboot team, that are difficult to keep track of
- Time is spent looking for links, or doing work that later is found to be duplicate or done wrong because a process or workflow was misunderstood or not shared for new team members

### Additional Information

[add]

      
### Tasks
1. Create folder that holds Source of Truth
2. Create Source of Truth document
3. Create first draft of document
4. Share with DDS team to collect input, feedback and more info in document

### Process Documentation
Source of Truth Folder:
https://ibm.box.com/s/whx3eyna683km504a8m5uw6hg6ub9edt

Source of Truth Document:

**Comment by sethibm** [comment]
@JennySanchez How does this look for task and goals?

**Comment by wonilsuhibm** [comment]
@jeffchew @sethibm how would you feel about adding this to the read me file of our two boards? 

The agile board
https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/README.md

The ideation board
https://github.com/carbon-design-system/digital-design-ideation/blob/master/README.md

**Comment by JennySanchez** [comment]
@sethibm Thank you for putting this togehter.

A few more resources to share with you to support the task:

**DDS Onboarding Checklist**
https://ibm.box.com/s/cameidzxkkihcziok3m0n7o0f35g0sri

**2020 DDS Team member onboarding experience improvement ideation**
https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579122568543?sender=chsanche&key=a949136c-920b-4aee-949d-35fd2fde51ca
