### ISSUE TITLE
Spacing audit

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#81]
### Objective
This story is to look at the existing patterns, with the goal of creating the following items:
- A system of types of spaces matched to components. Examples: container padding, outer spacing, inner spacing, gutter between repeating items, type pairing, etc. These are just random examples. This story is to find the right system(s) of classification.
- Dimensions/factors to consider
   - Text—text, text—image, image—image
   - The impact of sizes. Eg) large image—text VS small image—text
   - Heading and text location within page / narrative flow
- Focus on lowest level, simple, and repeating patterns within pages, that make up essential spacing flow

### Outputs
- Sketch file with following : visual, diagrammatic, information architecture around spacing for Learn and Solutions pages
- Inclusion of Hypotheses, Questions, Notes, and suggestions for new Components or update to existing Components based on this work
- Quantification of all repeating patterns identified at lowest levels of spacing 
- An Airtable spreadsheet reflecting the same information as above, but in spreadsheet format

### Additional notes
- Use learn and solutions as starting set to gather data and diagram
- Include services templates asap (Lila)

**Comment by sethibm** [comment]
Noting this related issue with the Linklist here.  Current spacing audit focuses on vertical padding, and this is a horizontal padding issue.  Deserves some attention, in terms of overall relational planning issue between components, at the template level.  

In this case, it's how to handle the container for the right side element like LinkList.  At the moment, the 8 column is essentially colliding with the linklist on the right.  In Learning template design, there is 94px padding on the 1312px breakpoint version.  The visual specs do not specify relationship here, in terms of columns, percentages, px, etc.  See attached.  

Jeff noted "this might be a question of how we handle the aside item for the contentblock, or if it's something we want it specific to the content being injected in...what we have enabled is not the linklist per se, but a container for a right side element where you can put anything in there. In this particular case, we are putting in the LinkList"

<img width="481" alt="Screen Shot 2020-07-06 at 2 44 46 PM" src="https://user-images.githubusercontent.com/58601040/86636420-41eed600-bfa2-11ea-822a-21ba70ad242d.png">

<img width="789" alt="Screen Shot 2020-07-06 at 2 25 50 PM" src="https://user-images.githubusercontent.com/58601040/86636417-40bda900-bfa2-11ea-9e34-a76e8df409a6.png">

**Comment by sethibm** [comment]
Met with Wonil, Lara, and James yesterday to review progress and confirm direction with this first step on the audit.  Confirmation of right direction.  Next steps: 

- finish the audit of Learn page
- move on to Solutions page next
- continue to isolate and diagram lowest level, repeating patterns and respective spacing
- continue to evolve visual diagram in Sketch, along with notes, questions and hypotheses
- explore creation of airtable spreadsheet as pure text / data companion to Sketch file

**Comment by ghost** [comment]
Moving back to backlog.

**Comment by JennySanchez** [comment]
Based on the short discussion, we need to connect with Lila for alignment.

For the short term, we will have a link on the website linking to the wiki page where the MVP spacing guideline will be hosted. Wonil and Jenny will discuss where to set up the link from the website and what the next iteration will look like.

**Comment by shixiedesign** [comment]
Great project brief but we'd have to revisit. Not one of the current priorities, and not a big fire right now.
