### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Elliott Trice) (scheduled 07/13)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#89]
### [Elliott Trice](https://w3.ibm.com/bluepages/profile.html?uid=5G5141897)
![Screen Shot 2020-07-06 at 5 42 38 PM](https://user-images.githubusercontent.com/45213839/86792047-b6238b00-c02f-11ea-95dd-19158afa6580.png)

Product Owner, IBM.com Reboot
IBM Cloud and Cognitive Software 

---

### Note

Elliott is the former head of DGC design and the current product owner of the IBM.com Reboot project. As such, he is responsible for two main things:
- Creating the new information architecture and navigation system for IBM.com
- Creating new templates and other bespoke page designs for the new IBM.com experience using IDL, Carbon, and IBM.com Library.

##### IBM.com Reboot program / team
This is a program that comprises mainly two squads: IBM.com Reboot squad and the Digital Design System squad. Within the Reboot squad, there are three main work streams: the IA/Nav, template design, and partner support.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Interview notes doc: https://ibm.box.com/s/98cud4p079i6rexje839933ypf2gmhg1
