### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Nigel Prentice) (scheduled 07/13)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#90]
### [Nigel Prentice](https://w3.ibm.com/bluepages/profile.html?uid=4G2167897)
![Screen Shot 2020-07-06 at 5 53 50 PM](https://user-images.githubusercontent.com/45213839/86792922-917be300-c030-11ea-878b-d4437e2d065c.png)

Design Director, Digital Growth & Commerce; F&O Support Experiences
IBM Cloud and Cognitive Software 

---

### Note

Nigel Prentice is the head of DGC design. As such, he oversees all designers in the various squads within DGC, as well as the Support design team.

He is the one who recognized the importance of the style models and initiated this second phase program.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Interview answers doc: https://ibm.box.com/s/6whqrieew4h60qautrts5wbdnowhopkj
