### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Linda Carotenuto) (scheduled 07/09)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#91]
### [Linda Carotenuto](https://w3.ibm.com/bluepages/profile.html?uid=L06810897)

![Screen Shot 2020-07-06 at 5 57 26 PM](https://user-images.githubusercontent.com/45213839/86793002-a48eb300-c030-11ea-901e-52b37dc601f4.png)

Offering Manager - Digital Design Squad - Carbon for ibm.com
IBM Cloud and Cognitive Software 

---

### Note

Linda is a long time IBMer with deep experiences and knowledge around the various IBM.com features and the overall landscape. She is currently the offering manager of the Digital Design System.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Interview script and (pending completion) answers: https://ibm.box.com/s/vf2nfpq1z0bkvwb26cuj5ogmq24shlk5

**Comment by oscardumlao-ibm** [comment]
Interview finished, recording uploaded, and responses noted on above document. Script has been migrated to a different Box Notes but is linked on the above doc as well.
