### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Mike Abbink) (scheduled 07/14)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#92]
### [Mike Abbink](https://w3.ibm.com/bluepages/profile.html?uid=5G0964897)

![Screen Shot 2020-07-06 at 5 59 14 PM](https://user-images.githubusercontent.com/45213839/86793190-d56ee800-c030-11ea-8027-a42b578fc5f1.png)

IBM Distinguished Designer, Executive Creative Director,  IBM Brand Experience and Design
IBM CHQ, Marketing 

---

### Note

Mike is an Executive Creative Director. As such, he led the Duo project that created the new IBM Design Language (IDL). He is currently overseeing the development and application of IDL and Carbon Design System across all IBM.

He is a long time type designer, and led the effort to conceptualize and create IBM's new typeface, IBM Plex.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Interview notes: https://ibm.box.com/s/txnqmf7tpncdn8xfsqulxhw6pkqp32jp

**Comment by oscardumlao-ibm** [comment]
Note: Mike could not make this and no interview was conducted. Will need to reschedule.

**Comment by ghost** [comment]
Moving back to the backlog.
