### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Sarah Brooks)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#93]
### [Sarah Brooks](https://w3.ibm.com/bluepages/profile.html?uid=0J4462897)

![Screen Shot 2020-07-06 at 6 01 50 PM](https://user-images.githubusercontent.com/45213839/86793226-ddc72300-c030-11ea-8177-6ced3a773c66.png)

Design Experience Executive, IBM Distinguished Designer
IBM Cloud and Cognitive Software 

---

### Note

Sarah used to be part of DGC as the owner of the IBM Journey System. As the Journey System project moved to a new home within IBM Design Program Office (DPO), she also moved to IBM DPO. Currently she is overseeing the next phase of the Journey System, which is the DUX review process.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Holdover from pre-Patterns program — no longer relevant to current work.
