### ISSUE TITLE
🥩 IBM.com style model work - stakeholder interview (Wonil Suh) - confirmed, date TBD by Patterns Team

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#96]
### [Wonil Suh](https://w3.ibm.com/bluepages/profile.html?uid=1J2729897)
![Screen Shot 2020-07-06 at 6 08 15 PM](https://user-images.githubusercontent.com/45213839/86794130-c177b600-c031-11ea-8c01-522c9dbb7d9d.png)

Design Lead, Digital Design System
IBM Cloud and Cognitive Software 

---

### Note

Wonil has been part of the development of the new IBM Design Language, and currently its application within IBM.com space. He is currently serving as the creative director for DGC design team, and the design lead for the DDS squad.

##### Your team
- [ ] Tell me who you are, what you do, and what is the mission of your team?
- [ ] What are your goals?
- [ ] What is your definition of success?
- [ ] Who are your users/adopters?
- [ ] What are your business needs?
- [ ] What are your fears?
- [ ] What are your pain points?

##### Style Models
- [ ] Are you aware of the inconsistent experiences on IBM.com?
- [ ] Is your team involved in addressing the inconsistency issues on IBM.com? If so, how?
- [ ] Are you aware of the IBM.com Style Models project?
- [ ] How do you see this be operational for your team?
- [ ] What do you hope the IBM.com Style Models do or bring to your team/BU?
- [ ] Sharing the design intents --> Are there other design intents missing from what I just shared?

**Comment by oscardumlao-ibm** [comment]
Patterns project concluded, so not relevant anymore. We touched base several times with Wonil outside of the structure of a stakeholder interview.
